### ISSUE TITLE
feedback from review

### ISSUE THREAD

**Issue by pdurbin** [gdcc/dvwebloader#11]
I'm reviewing the code on the Dataverse side at https://github.com/IQSS/dataverse/pull/9096 and plan to use this issue to list bugs and typos I find:

- typo: "aftterwards"
- "Help/Tutorial" links to https://github.com/gdcc/dvwebloader/wiki/DVWebloader---a-bulk-file-uploader-for-Dataverse which prompts the user to create a new wiki page.
- green "upload complete" when it actually failed (see screenshot below)
- API token shown by console.log
- ...

![Screen Shot 2022-12-21 at 2 59 06 PM](https://user-images.githubusercontent.com/21006/208993165-3e98e2e1-48b1-44a7-a049-166a79646e28.png)

**Comment by qqmyers** [comment]
Fixed the doc-related issues. Will leave open for the code changes.
