### ISSUE TITLE
Multipart file upload failing relative to S3 direct upload

### ISSUE THREAD

**Issue by Louis-wr** [gdcc/dvwebloader#7]
### Current behavior:

When using dvwebloader  to upload a file that uses multipart upload the upload of said files appears to fail with error 401.
This is coming form dvwebloader since the same same is uploaded with no difficulty when uploaded using the normal dataverse interface.

From the logs it looks like the proper api key is not being passed in that case.
```

[#|2022-10-06T07:42:43.035+0000|WARNING|Payara 5.2021.1|edu.harvard.iq.dataverse.util.BundleUtil|_ThreadID=97;_ThreadName=http-thread-pool::jk-connector(5);_TimeMillis=1665042163035;_LevelValue=900;|
  Could not find key "externaltools.dvwebloader.displayname" in bundle file: |#

```
### Expected behavior :

the File being uploaded

### Reproducing steps :

Upload a file that uses multipart upload. Currently on https://test-docker.dataverse.no/ the part size is about 1gB.

**Comment by qqmyers** [comment]
Is that still true after https://github.com/gdcc/dvwebloader/commit/2ad66c23595f24247628ae3884a28a83d1eff862 was added yesterday?

**Comment by Louis-wr** [comment]
The warning error still appears but it must be unrelated  since the files gets uploaded without any problems https://github.com/gdcc/dvwebloader/commit/2ad66c23595f24247628ae3884a28a83d1eff862**** must have fixed the issue.

**Comment by qqmyers** [comment]
Good. Yeah, the warning error is for any tool - one can now add their display names in the properties files, which allows for internationalization, but if you don't have such entries, the warning appears.
